# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=13, null=True)),
                ('status', models.BooleanField(default=False)),
                ('device', models.CharField(max_length=50, null=True)),
                ('influencer', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
