# Generated by Django 2.2.7 on 2020-02-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictureurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auid', models.CharField(max_length=13, null=True)),
                ('title', models.CharField(max_length=100)),
                ('image_path', models.TextField()),
                ('details', models.TextField(null=True)),
                ('file_name', models.CharField(max_length=100)),
                ('short_link', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hyperlink', models.CharField(max_length=220, null=True)),
                ('action', models.CharField(max_length=13, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=250)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('campaign_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictureURL.Pictureurl')),
            ],
        ),
    ]
