# Generated by Django 2.2.7 on 2019-12-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictureURL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictureurl',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='pictureurl',
            old_name='uid',
            new_name='auid',
        ),
    ]
