# Generated by Django 2.2.7 on 2019-12-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictureURL', '0002_auto_20191209_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureurl',
            name='short_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=250)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('campaign_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictureURL.Pictureurl')),
            ],
        ),
    ]
