# Generated by Django 2.2.7 on 2019-12-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureURL', '0003_auto_20191217_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureurl',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
