# Generated by Django 2.2.7 on 2020-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureURL', '0004_pictureurl_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
